services:
    mssql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        container_name: mssql-server
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Password.1234"
        ports:
            - "1433:1433"
    seq:
        image: datalust/seq:latest
        container_name: seq
        ports:
            - "5341:80"
        environment:
            ACCEPT_EULA: "Y"
        restart: unless-stopped
        depends_on:
            - mssql-server
    redis-cache:
        container_name: redis-cache
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --bind redis-cache --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81 --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes --loglevel warning
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
    plantcare-api:
        build: ./PlantCare.API
        container_name: plantcare-api
        environment:
            DatabaseServer: "mssql-server"
            DatabasePort: "1433"
            DatabaseUser: "sa"
            DatabasePassword: "Password.1234"
            ReadDatabaseName: "PlantCare_Read_DB"
            WriteDatabaseName: "PlantCare_Write_DB"
            RedisConnectionString: "redis-cache:6379"
            RedisPassword: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
            RedisInstance: "plantcare"
            SpecificCorsOrigin: "http://192.168.1.42:3000"
            MessageBrokerHostName: "rabbitmq"
            MessageBrokerPort: "5672"
            MessageBrokerUsername: "guest"
            MessageBrokerPassword: "guest"
        depends_on:
            - rabbitmq
            - seq
            - redis-cache
        ports:
            - "8080:8080"

